### ISSUE TITLE
Submitting CoderSchool iOS Prework

### ISSUE THREAD

**Issue by dqhieu** [dqhieu/TipCalculator#1]
Here is my completed prework Tip Calculator. Thank you!

/cc @coderschoolreview

**Comment by minhchau273** [comment]
👍 Congratulation on finishing the Tip Calculator with the nice UI. Your app looks great.

#### Some small comments:
- Looks like you've already had the experience with iOS development before. You even use the auto layout and `UIGestureRecognizer`. 😉 
- Good usage of the `NSUserDefault`. This is one of the methods to pass data between view controllers.
- Nice idea with the pan gesture but it's a little bit hard for users to pan it to their expected percentage exactly.
- You shouldn't let user input the invalid min and max values in Settings, should you? Although you've validated them but you did it in silence. Users don't know you reset the min and max values to the same one util they go back the Settings. I though the pan gesture doesn't work well cuz I try panning the total amount but nothing happens.
- Your app crashed when I paste some text to the amount text field.  
  <img width="753" alt="screen shot 2016-06-26 at 6 30 56 pm" src="https://cloud.githubusercontent.com/assets/12395213/16362002/2cd17ac4-3bcc-11e6-934a-c88a82ce7674.png">

Excellent submission overall 🍡

**Comment by dqhieu** [comment]
@minhchau273 Thank you for your review! I will fix it soon!
